apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: mongodb-replica
spec:
  members: 3
  version: "4.2.6"
  project: mongodbProject
  credentials: my-credentials
  type: ReplicaSet
  podSpec:
    memory: "300M"
    persistence:
      single:
        storage: "50Gi"
  security:
    authentication:
      modes: [ "SCRAM" ]
  users:
    - name: my-user
      db: admin
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: my-user-password
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
      scramCredentialsSecretName: my-scram
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib