apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: mongodb-replicaset
spec:
  members: 3
  type: ReplicaSet
  version: "4.2.6"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: admin
      db: admin
      passwordSecretRef:
        name: password-admin
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
      scramCredentialsSecretName: admin-scram
    - name: vaultuser
      db: admin
      passwordSecretRef:
        name: password-user1
      roles:
        - name: readWrite
          db: vault
      scramCredentialsSecretName: user-scram1
  statefulSet:
    spec:
        serviceName: test-mongodb-svc
        selector: { }
        template:
          spec:
            containers:
              - name: mongodb-agent
                volumeMounts:
                  - name: mongod-pvc
                    mountPath: /my-custom-version/mount-path
            volumeClaimTemplates:
              - metadata:
                  name: mongod-pvc
                spec:
                  storageClassName: ""
                  accessModes: [ "ReadWriteOnce" ]
                  resources:
                    requests:
                      storage: 20Gi
#  statefulSet:
#    spec:
##      serviceName: mongodb-statefulset
##      selector: {}
##      template:
##        spec:
##          containers:
##            - name: mongod
##              volumeMounts:
##                - name: mongod-pvc
##                  mountPath: /data/mongod
##            - name: mongodb-agent
##              volumeMounts:
##                - name: mongo-agent-pvc
##                  mountPath: /data/agent
#      volumeClaimTemplates:
#        - metadata:
#            name: mongod-pvc
#          spec:
#            storageClassName: mongod-sc
#            accessModes: [ "ReadWriteOnce" ]
#            resources:
#              requests:
#                storage: 20Gi
#        - metadata:
#            name: mongo-agent-pvc
#          spec:
#            storageClassName: mongo-agent-sc
#            accessModes: [ "ReadWriteOnce" ]
#            resources:
#              requests:
#                storage: 20Gi

---
apiVersion: v1
kind: Secret
metadata:
  name: password-admin
type: Opaque
stringData:
  password: "admin"
---
apiVersion: v1
kind: Secret
metadata:
  name: password-user1
type: Opaque
stringData:
  password: "123456789"